export const SITE_URL = 'https://touringexpertsale.ru';

export const TEST_USER = {
  tgId: 'test-user-001',
  username: 'alex_touring',
  firstName: 'Александр',
  lastName: 'Петров',
  email: 'alex@touringexpert.ru',
  phone: '+7 (999) 123-45-67',
  photoUrl: 'https://i.pravatar.cc/200?img=12',
  city: { id: '1', name: 'Москва', country: { id: '1', name: 'Россия' } },
  country: 'Россия',
  subscribedToNewsletter: false,
  emailVerified: true,
  url: `${SITE_URL}/test/user`,
};

export const TEST_BRAND = {
  id: 'test-brand-001',
  name: 'ТЕСТ',
  photo: 'https://picsum.photos/seed/touring-brand/400/400',
  contact: 'https://t.me/touringexpert',
  description:
    'Тестовый бренд для проверки функционала платформы Touring Expert. Предлагаем качественное мотооборудование и снаряжение для любителей активного туризма и мотопутешествий.',
  displayOrder: 1,
  isActive: true,
  productCount: 16,
  url: `${SITE_URL}/test/brand`,
};

export const TEST_CATEGORIES = [
  {
    slug: 'shlemy',
    name: 'Шлемы',
    description:
      'Широкий выбор мотошлемов: интеграл, трансформер, открытый, кроссовый. Бренды AGV, Shoei, HJC, Arai и другие.',
  },
  {
    slug: 'motokurtki',
    name: 'Мотокуртки',
    description:
      'Защитные мотокуртки из кожи и текстиля. Летние и всесезонные модели с сертифицированной защитой CE.',
  },
  {
    slug: 'motozaschita',
    name: 'Мотозащита',
    description:
      'Защитная мотоэкипировка: черепахи, наколенники, налокотники, защита спины уровня CE Level 2.',
  },
  {
    slug: 'motobotinki',
    name: 'Мотоботинки',
    description:
      'Мотоботинки и мотосапоги для городской езды, туризма и спорта. Водонепроницаемые модели Gore-Tex.',
  },
] as const;

export type CategorySlug = (typeof TEST_CATEGORIES)[number]['slug'];

const BRAND = {
  id: 'test-brand-001',
  name: 'ТЕСТ',
  photo: 'https://picsum.photos/seed/touring-brand/400/400',
  contact: 'https://t.me/touringexpert',
  description: 'Тестовый бренд',
};

const USER = {
  tgId: 'test-user-001',
  username: 'alex_touring',
  firstName: 'Александр',
  lastName: 'Петров',
  email: 'alex@touringexpert.ru',
  phone: '+7 (999) 123-45-67',
  photoUrl: 'https://i.pravatar.cc/200?img=12',
  city: null,
};

export const TEST_PRODUCTS = [
  // ── Шлемы ──────────────────────────────────────────────────────
  {
    id: 'prod-sh-001',
    slug: 'agv-k6-s',
    name: 'AGV K6 S',
    categorySlug: 'shlemy' as CategorySlug,
    category: { id: 'cat-shlemy', name: 'Шлемы' },
    priceCash: '45000',
    priceNonCash: '47700',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/helmet-agv/600/600',
    files: [
      'https://picsum.photos/seed/helmet-agv-2/600/600',
      'https://picsum.photos/seed/helmet-agv-3/600/600',
    ],
    description:
      'Спортивный шлем-интеграл AGV K6 S — воплощение итальянского дизайна и передовых технологий. Карбоновая оболочка обеспечивает максимальную защиту при минимальном весе 1350 г.\n\nСистема вентиляции NEXT с 7 каналами подачи и 3 каналами вывода воздуха гарантирует отличную циркуляцию. Подкладка из материала Shalimar Premium для комфорта при длительных поездках. Визор IridiumFlex с быстросъёмной системой.',
    isNew: true,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 5,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 142,
  },
  {
    id: 'prod-sh-002',
    slug: 'hjc-rpha-11',
    name: 'HJC RPHA 11 Carbon',
    categorySlug: 'shlemy' as CategorySlug,
    category: { id: 'cat-shlemy', name: 'Шлемы' },
    priceCash: '38000',
    priceNonCash: '40280',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/helmet-hjc/600/600',
    files: ['https://picsum.photos/seed/helmet-hjc-2/600/600'],
    description:
      'Шлем HJC RPHA 11 Carbon создан для гонщиков, которые не идут на компромиссы. Оболочка P.I.M.+ из карбона и органического волокна весит всего 1270 г — один из самых лёгких шлемов в своём классе.\n\nАэродинамический профиль снижает подъёмную силу на скоростях от 150 км/ч. Система вентиляции ACS с 5 продухами.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 3,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 98,
  },
  {
    id: 'prod-sh-003',
    slug: 'shoei-x-spr-pro',
    name: 'Shoei X-SPR Pro',
    categorySlug: 'shlemy' as CategorySlug,
    category: { id: 'cat-shlemy', name: 'Шлемы' },
    priceCash: '67000',
    priceNonCash: '71020',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/helmet-shoei/600/600',
    files: ['https://picsum.photos/seed/helmet-shoei-2/600/600'],
    description:
      'Флагманский гоночный шлем Shoei X-SPR Pro разработан совместно с командами MotoGP. Оболочка AIM+ из стекловолокна, органики и кевлара. Вес от 1480 г при сертификации FIM 8859.\n\nВизор CWR-F2 с зеркальным покрытием обеспечивает исключительную оптическую чистоту. Система QRSP для быстрой замены визора без инструментов.',
    isNew: true,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 2,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 211,
  },
  {
    id: 'prod-sh-004',
    slug: 'bell-race-star-flex',
    name: 'Bell Race Star Flex DLX',
    categorySlug: 'shlemy' as CategorySlug,
    category: { id: 'cat-shlemy', name: 'Шлемы' },
    priceCash: '52000',
    priceNonCash: '55120',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/helmet-bell/600/600',
    files: ['https://picsum.photos/seed/helmet-bell-2/600/600'],
    description:
      'Bell Race Star Flex DLX оснащён технологией Flex Energy Management — многоуровневой системой поглощения ударов, снижающей ротационные ускорения на 30%.\n\nКарбоновая оболочка, встроенная солнцезащитная шторка Transitions, система блокировки визора MagneFusion. Система регулировки размера Fit System для идеальной посадки.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 4,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 87,
  },

  // ── Мотокуртки ─────────────────────────────────────────────────
  {
    id: 'prod-mk-001',
    slug: 'alpinestars-gp-plus-r3',
    name: 'Alpinestars GP Plus R v3',
    categorySlug: 'motokurtki' as CategorySlug,
    category: { id: 'cat-motokurtki', name: 'Мотокуртки' },
    priceCash: '35000',
    priceNonCash: '37100',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/jacket-alpinestars/600/600',
    files: ['https://picsum.photos/seed/jacket-alpinestars-2/600/600'],
    description:
      'Спортивная кожаная куртка Alpinestars GP Plus R v3 для трек-дней и агрессивной дорожной езды. Натуральная коровья кожа 1.3 мм с перфорацией для вентиляции.\n\nВстроенная защита плеч и локтей Alpinestars Nucleon Flex Plus CE Level 1. Карман для вставки защиты спины. Эластичные вставки на локтях и пояснице.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 6,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 76,
  },
  {
    id: 'prod-mk-002',
    slug: 'dainese-super-speed-4',
    name: 'Dainese Super Speed 4',
    categorySlug: 'motokurtki' as CategorySlug,
    category: { id: 'cat-motokurtki', name: 'Мотокуртки' },
    priceCash: '42000',
    priceNonCash: '44520',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/jacket-dainese/600/600',
    files: ['https://picsum.photos/seed/jacket-dainese-2/600/600'],
    description:
      'Dainese Super Speed 4 — кожаная куртка с технологией поглощения удара Tutu и встроенной защитой позвоночника Pro-Shape 2.0 CE Level 2. Гибридный дизайн сочетает перфорированные кожаные панели с тканевыми вставками.\n\nСистема Ergonomics System для регулировки подгонки. Светоотражающие элементы для повышения видимости.',
    isNew: true,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 4,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 134,
  },
  {
    id: 'prod-mk-003',
    slug: 'revit-ignition-4-h2o',
    name: "REV'IT Ignition 4 H2O",
    categorySlug: 'motokurtki' as CategorySlug,
    category: { id: 'cat-motokurtki', name: 'Мотокуртки' },
    priceCash: '28000',
    priceNonCash: '29680',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/jacket-revit/600/600',
    files: ['https://picsum.photos/seed/jacket-revit-2/600/600'],
    description:
      "REV'IT Ignition 4 H2O — всесезонная мотокуртка с мембраной H2Out для защиты от дождя. Кожаная куртка с водонепроницаемой подкладкой сохраняет стиль в любую погоду.\n\nВстроенные протекторы плеч и локтей CE Level 1. Карман для защиты спины. Совместима с мотоштанами через молнию 3/4.",
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 8,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 55,
  },
  {
    id: 'prod-mk-004',
    slug: 'klim-apex',
    name: 'KLIM Apex Jacket',
    categorySlug: 'motokurtki' as CategorySlug,
    category: { id: 'cat-motokurtki', name: 'Мотокуртки' },
    priceCash: '55000',
    priceNonCash: '58300',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/jacket-klim/600/600',
    files: ['https://picsum.photos/seed/jacket-klim-2/600/600'],
    description:
      'KLIM Apex — премиальная экспедиционная куртка для дальних мотопутешествий. Мембрана GORE-TEX Pro обеспечивает абсолютную водонепроницаемость и воздухопроницаемость.\n\nПротекторы D3O LP1 на плечах и локтях CE Level 2, спинная защита D3O LP2 CE Level 2 в комплекте. 17 карманов. Съёмная тёплая подкладка для езды до -10°C.',
    isNew: true,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 2,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 189,
  },

  // ── Мотозащита ─────────────────────────────────────────────────
  {
    id: 'prod-mz-001',
    slug: 'alpinestars-bionic-7-carbon',
    name: 'Alpinestars Bionic-7 Carbon',
    categorySlug: 'motozaschita' as CategorySlug,
    category: { id: 'cat-motozaschita', name: 'Мотозащита' },
    priceCash: '18000',
    priceNonCash: '19080',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/armor-alpinestars/600/600',
    files: ['https://picsum.photos/seed/armor-alpinestars-2/600/600'],
    description:
      'Защитный жилет Alpinestars Bionic-7 Carbon с карбоновыми вставками на грудной пластине. Защита CE Level 2 спины и CE Level 1 груди. Анатомическая конструкция повторяет контуры тела.\n\nВстроенные протекторы плеч и локтей CE Level 2. Полиуретановая боковая защита. 7 зон регулировки для идеальной посадки.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 5,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 63,
  },
  {
    id: 'prod-mz-002',
    slug: 'dainese-pro-armor',
    name: 'Dainese Pro-Armor Evolution',
    categorySlug: 'motozaschita' as CategorySlug,
    category: { id: 'cat-motozaschita', name: 'Мотозащита' },
    priceCash: '12000',
    priceNonCash: '12720',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/armor-dainese/600/600',
    files: ['https://picsum.photos/seed/armor-dainese-2/600/600'],
    description:
      'Dainese Pro-Armor Evolution — лёгкий и компактный защитный жилет для ношения под мотоодеждой. Вес всего 680 г при защите CE Level 1 спины, плеч и боков.\n\nЭргономичный дизайн не стесняет движения. Сетчатый материал сохраняет прохладу в жаркую погоду. Быстрозастёгивающаяся система buckle.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 10,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 47,
  },
  {
    id: 'prod-mz-003',
    slug: 'leatt-5-5-pro',
    name: 'Leatt 5.5 Pro HD Knee Guard',
    categorySlug: 'motozaschita' as CategorySlug,
    category: { id: 'cat-motozaschita', name: 'Мотозащита' },
    priceCash: '22000',
    priceNonCash: '23320',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/armor-leatt/600/600',
    files: ['https://picsum.photos/seed/armor-leatt-2/600/600'],
    description:
      'Наколенники Leatt 5.5 Pro HD с жёсткой пластиковой защитой и мягким вкладышем EPS. Сертифицированы по стандарту EN 13634 Level 1.\n\nАнатомическая форма для левого и правого колена. 4 точки крепления включают ремень выше и ниже колена. Перфорированная подкладка отводит влагу и обеспечивает вентиляцию.',
    isNew: true,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 7,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 82,
  },
  {
    id: 'prod-mz-004',
    slug: 'fox-titan-race-jacket',
    name: 'FOX Titan Race Jacket',
    categorySlug: 'motozaschita' as CategorySlug,
    category: { id: 'cat-motozaschita', name: 'Мотозащита' },
    priceCash: '16000',
    priceNonCash: '16960',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/armor-fox/600/600',
    files: ['https://picsum.photos/seed/armor-fox-2/600/600'],
    description:
      'FOX Titan Race Jacket — кроссовая защитная куртка для эндуро и мотокросса. Жёсткие пластиковые пластины на плечах, локтях и спине CE Level 1. Лёгкая сетчатая конструкция для максимальной вентиляции.\n\nСовместима со всеми шортами и штанами FOX через систему connector clips. Пакет защиты сертифицирован для соревнований.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 4,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 71,
  },

  // ── Мотоботинки ────────────────────────────────────────────────
  {
    id: 'prod-mb-001',
    slug: 'alpinestars-smx-6-v2',
    name: 'Alpinestars SMX-6 V2',
    categorySlug: 'motobotinki' as CategorySlug,
    category: { id: 'cat-motobotinki', name: 'Мотоботинки' },
    priceCash: '24000',
    priceNonCash: '25440',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/boots-alpinestars/600/600',
    files: ['https://picsum.photos/seed/boots-alpinestars-2/600/600'],
    description:
      'Alpinestars SMX-6 V2 — универсальные мотоботинки для трека и улицы. Микрофибровый верх с вставками из натуральной кожи. Защита лодыжки внутренней жёсткой вставкой CE Level 2.\n\nРегулируемые усиленные манжеты голеностопа. Термопластиковая защита пяточной области. Гибкая подошва Micro Vent для отличной тактильной обратной связи.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 6,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 114,
  },
  {
    id: 'prod-mb-002',
    slug: 'dainese-trq-tour-gore-tex',
    name: 'Dainese TRQ-Tour Gore-Tex',
    categorySlug: 'motobotinki' as CategorySlug,
    category: { id: 'cat-motobotinki', name: 'Мотоботинки' },
    priceCash: '30000',
    priceNonCash: '31800',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/boots-dainese/600/600',
    files: ['https://picsum.photos/seed/boots-dainese-2/600/600'],
    description:
      'Туристические мотосапоги Dainese TRQ-Tour Gore-Tex с мембраной GORE-TEX. Высокое голенище 27 см надёжно защищает голень.\n\nЖёсткая защита щиколоток и пяток. Встроенная пластина под пятку против скручивания голеностопа. Рефлективные элементы. Молния на всю длину голени для удобного надевания.',
    isNew: true,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 3,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 96,
  },
  {
    id: 'prod-mb-003',
    slug: 'sidi-canyon',
    name: 'Sidi Canyon Gore-Tex',
    categorySlug: 'motobotinki' as CategorySlug,
    category: { id: 'cat-motobotinki', name: 'Мотоботинки' },
    priceCash: '26000',
    priceNonCash: '27560',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/boots-sidi/600/600',
    files: ['https://picsum.photos/seed/boots-sidi-2/600/600'],
    description:
      'Sidi Canyon Gore-Tex — эндуро/туристические ботинки итальянского производства. Термопластиковая рамочная конструкция с системой регулировки по голени и подъёму. Сертификат CE Cat. II уровень 2.\n\nМембрана Gore-Tex для защиты от воды. Манжета с регулируемой жёсткостью. Быстросменная подошва Lorica.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 5,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 78,
  },
  {
    id: 'prod-mb-004',
    slug: 'tcx-comp-evo-michelin',
    name: 'TCX Comp Evo Michelin',
    categorySlug: 'motobotinki' as CategorySlug,
    category: { id: 'cat-motobotinki', name: 'Мотоботинки' },
    priceCash: '19000',
    priceNonCash: '20140',
    currency: 'RUB' as const,
    preview: 'https://picsum.photos/seed/boots-tcx/600/600',
    files: ['https://picsum.photos/seed/boots-tcx-2/600/600'],
    description:
      'TCX Comp Evo Michelin — эндуро-ботинки с подошвой от Michelin для превосходного сцепления на любом покрытии. Система Dual Closure обеспечивает фиксацию в 2 точках.\n\nПроводная термопластиковая конструкция защищает от скручивания голеностопа. Встроенная защита пятки и пальцев. Подкладка DrytexMembrane.',
    isNew: false,
    isFavorite: false,
    status: 'approved' as const,
    quantity: 9,
    quantityType: 'piece' as const,
    isActive: true,
    isDeleted: false,
    brand: BRAND,
    user: USER,
    viewCount: 53,
  },
];

export type TestProduct = (typeof TEST_PRODUCTS)[number];
